"""session expiry and login attempts

Revision ID: bdbbc33e6aa4
Revises: f26ad0398fc0
Create Date: 2026-09-19 01:08:59.067529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbbc33e6aa4'
down_revision: Union[str, None] = 'f26ad0398fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_created_at'), 'login_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    # Колонка NOT NULL, а сесії вже можуть існувати — тому в два кроки:
    # спершу додаємо nullable, наявним сесіям ставимо строк, потім вмикаємо NOT NULL.
    op.add_column('sessions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE sessions SET expires_at = created_at + interval '7 days'")
    op.alter_column('sessions', 'expires_at', nullable=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_column('sessions', 'expires_at')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
